# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'misc/toolbox.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_toolbox(object):
    def setupUi(self, toolbox):
        toolbox.setObjectName("toolbox")
        toolbox.resize(300, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(toolbox.sizePolicy().hasHeightForWidth())
        toolbox.setSizePolicy(sizePolicy)
        toolbox.setMinimumSize(QtCore.QSize(300, 500))
        toolbox.setMaximumSize(QtCore.QSize(300, 500))
        icon = QtGui.QIcon.fromTheme("insert-image")
        toolbox.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(toolbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(toolbox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -37, 266, 542))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.io_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.io_group.sizePolicy().hasHeightForWidth())
        self.io_group.setSizePolicy(sizePolicy)
        self.io_group.setMinimumSize(QtCore.QSize(0, 100))
        self.io_group.setObjectName("io_group")
        self.gridLayout = QtWidgets.QGridLayout(self.io_group)
        self.gridLayout.setObjectName("gridLayout")
        self.io_bt_load = QtWidgets.QPushButton(self.io_group)
        self.io_bt_load.setObjectName("io_bt_load")
        self.gridLayout.addWidget(self.io_bt_load, 0, 0, 1, 1)
        self.io_bt_save = QtWidgets.QPushButton(self.io_group)
        self.io_bt_save.setEnabled(False)
        self.io_bt_save.setObjectName("io_bt_save")
        self.gridLayout.addWidget(self.io_bt_save, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.io_group)
        self.image_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_group.sizePolicy().hasHeightForWidth())
        self.image_group.setSizePolicy(sizePolicy)
        self.image_group.setMinimumSize(QtCore.QSize(0, 100))
        self.image_group.setObjectName("image_group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.image_group)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.image_bt_show_original = QtWidgets.QPushButton(self.image_group)
        self.image_bt_show_original.setEnabled(False)
        self.image_bt_show_original.setObjectName("image_bt_show_original")
        self.gridLayout_2.addWidget(self.image_bt_show_original, 0, 0, 1, 1)
        self.image_bt_reset = QtWidgets.QPushButton(self.image_group)
        self.image_bt_reset.setEnabled(False)
        self.image_bt_reset.setObjectName("image_bt_reset")
        self.gridLayout_2.addWidget(self.image_bt_reset, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.image_group)
        self.transform_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transform_group.sizePolicy().hasHeightForWidth())
        self.transform_group.setSizePolicy(sizePolicy)
        self.transform_group.setMinimumSize(QtCore.QSize(0, 100))
        self.transform_group.setObjectName("transform_group")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.transform_group)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.transform_bt_h_flip = QtWidgets.QPushButton(self.transform_group)
        self.transform_bt_h_flip.setEnabled(False)
        self.transform_bt_h_flip.setObjectName("transform_bt_h_flip")
        self.gridLayout_3.addWidget(self.transform_bt_h_flip, 0, 0, 1, 1)
        self.transform_bt_v_flip = QtWidgets.QPushButton(self.transform_group)
        self.transform_bt_v_flip.setEnabled(False)
        self.transform_bt_v_flip.setObjectName("transform_bt_v_flip")
        self.gridLayout_3.addWidget(self.transform_bt_v_flip, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.transform_group)
        self.color_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_group.sizePolicy().hasHeightForWidth())
        self.color_group.setSizePolicy(sizePolicy)
        self.color_group.setMinimumSize(QtCore.QSize(0, 75))
        self.color_group.setObjectName("color_group")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.color_group)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.color_bt_luminance = QtWidgets.QPushButton(self.color_group)
        self.color_bt_luminance.setEnabled(False)
        self.color_bt_luminance.setObjectName("color_bt_luminance")
        self.gridLayout_4.addWidget(self.color_bt_luminance, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.color_group)
        self.quantization_group = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.quantization_group.setMinimumSize(QtCore.QSize(0, 125))
        self.quantization_group.setObjectName("quantization_group")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.quantization_group)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.quantization_spin_tones = QtWidgets.QSpinBox(self.quantization_group)
        self.quantization_spin_tones.setMinimum(1)
        self.quantization_spin_tones.setMaximum(256)
        self.quantization_spin_tones.setProperty("value", 256)
        self.quantization_spin_tones.setObjectName("quantization_spin_tones")
        self.gridLayout_5.addWidget(self.quantization_spin_tones, 0, 1, 1, 1)
        self.quantization_spin_label_tones = QtWidgets.QLabel(self.quantization_group)
        self.quantization_spin_label_tones.setObjectName("quantization_spin_label_tones")
        self.gridLayout_5.addWidget(self.quantization_spin_label_tones, 0, 0, 1, 1)
        self.quantization_bt_quantize = QtWidgets.QPushButton(self.quantization_group)
        self.quantization_bt_quantize.setEnabled(False)
        self.quantization_bt_quantize.setObjectName("quantization_bt_quantize")
        self.gridLayout_5.addWidget(self.quantization_bt_quantize, 2, 0, 1, 2)
        self.quantization_radio_random = QtWidgets.QRadioButton(self.quantization_group)
        self.quantization_radio_random.setChecked(True)
        self.quantization_radio_random.setObjectName("quantization_radio_random")
        self.gridLayout_5.addWidget(self.quantization_radio_random, 1, 0, 1, 1)
        self.quantization_radio_kmeans = QtWidgets.QRadioButton(self.quantization_group)
        self.quantization_radio_kmeans.setObjectName("quantization_radio_kmeans")
        self.gridLayout_5.addWidget(self.quantization_radio_kmeans, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.quantization_group)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(toolbox)
        QtCore.QMetaObject.connectSlotsByName(toolbox)

    def retranslateUi(self, toolbox):
        _translate = QtCore.QCoreApplication.translate
        toolbox.setWindowTitle(_translate("toolbox", "Photochopp - Toolbox"))
        self.io_group.setTitle(_translate("toolbox", "IO"))
        self.io_bt_load.setText(_translate("toolbox", "Load image"))
        self.io_bt_save.setText(_translate("toolbox", "Save working image"))
        self.image_group.setTitle(_translate("toolbox", "Image"))
        self.image_bt_show_original.setText(_translate("toolbox", "Show/hide original image"))
        self.image_bt_reset.setText(_translate("toolbox", "Reset working image"))
        self.transform_group.setTitle(_translate("toolbox", "Transform"))
        self.transform_bt_h_flip.setText(_translate("toolbox", "Flip Horizontally"))
        self.transform_bt_v_flip.setText(_translate("toolbox", "Flip Vertically"))
        self.color_group.setTitle(_translate("toolbox", "Color"))
        self.color_bt_luminance.setText(_translate("toolbox", "Luminance"))
        self.quantization_group.setTitle(_translate("toolbox", "Quantization"))
        self.quantization_spin_label_tones.setText(_translate("toolbox", "# of tones"))
        self.quantization_bt_quantize.setText(_translate("toolbox", "Quantize"))
        self.quantization_radio_random.setText(_translate("toolbox", "Random"))
        self.quantization_radio_kmeans.setText(_translate("toolbox", "KMeans"))

